/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.Fornecedor;
import persistencia.FornecedorDAO;
import persistencia.IFornecedorDAO;

/**
 *
 * @author USUARIO
 */
public class fmListarFornecedores extends javax.swing.JFrame {
    
    
// Variável para guardar a referência do painel principal
        // Variável para guardar QUEM chamou essa tela
    private fmFornecedores janelaMae; 

    // Método para o fmPaciente se identificar
    public void setJanelaMae(fmFornecedores f) {
        this.janelaMae = f;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fmListarFornecedores.class.getName());

    /**
     * Creates new form fmListarpacientes
     */
    public fmListarFornecedores() {
        initComponents();
        // Adicione esta linha para bloquear a edição na tabela inteira:
        jtFornecedores.setDefaultEditor(Object.class, null);
    }
    
    // Método público para receber o Desktop do fmPrincipal
    public void setDesktop(javax.swing.JDesktopPane d) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtFornecedores = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Pacientes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtFornecedores);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Localizar paciente:");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listar Fornecedores");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\UERJ-Engenharia_Sist_Computacao\\Semestre 2025-2\\CLP\\Projeto\\Consultorio\\src\\main\\java\\resources\\Search-32.png")); // NOI18N
        jButton1.setText("Localizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Chamamos ao método listar da Classe DAO
        IFornecedorDAO dao = new FornecedorDAO();
        List<Fornecedor> lista = dao.listarTodos();
        
        // criando um modelo para a tabela
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nome");
        modelo.addColumn("Telefone");
        
        //adicionamos os itens à tabela
        for (Fornecedor paciente: lista){
            modelo.addRow(new Object[]{paciente.getIdFornecedor(), paciente.getNome(), paciente.getTelefone()});
        }
        
        // dar o modelo à tabela paciente
        jtFornecedores.setModel(modelo);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // Pegar o texto da caixa
            String nomePesquisa = jTextField1.getText();

            // Chamar o DAO
            FornecedorDAO dao = new FornecedorDAO();
            List<Fornecedor> lista = dao.buscarPorNome(nomePesquisa);

            // Atualizar a tabela
            DefaultTableModel modelo = (DefaultTableModel) jtFornecedores.getModel();
            modelo.setNumRows(0); // Limpa a tabela atual

            for (Fornecedor p : lista) {
                modelo.addRow(new Object[]{
                    p.getIdFornecedor(), // Coluna 0 (ID)
                    p.getNome(),       // Coluna 1
                    p.getTelefone()    // Coluna 2
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar: " + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFornecedoresMouseClicked
        if (evt.getClickCount() == 2) {
            // Pega o ID da tabela
            int linha = jtFornecedores.getSelectedRow();
            if (linha == -1) return; // Proteção

            int id = Integer.parseInt(jtFornecedores.getValueAt(linha, 0).toString());

            // Busca o objeto completo no banco
            FornecedorDAO dao = new FornecedorDAO();
            Fornecedor fornecedorCompleto = dao.getByID(id);

            // A MÁGICA: Devolve para a janela que estava aberta
            if (janelaMae != null) {
                janelaMae.preencherEdicao(fornecedorCompleto); // Manda os dados
                this.dispose(); // Fecha a tela de pesquisa
            } else {
                JOptionPane.showMessageDialog(null, "Erro: Janela de origem não identificada.");
            }
        }
    }//GEN-LAST:event_jtFornecedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fmListarFornecedores().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jtFornecedores;
    // End of variables declaration//GEN-END:variables
}
